### ISSUE TITLE
get features in realtime

### ISSUE THREAD

**Issue by aniketzz** [audeering/opensmile-python#50] opened 2021-12-10 14:01 UTC
What will be the way to use FFmpeg with the python API? 
How do I get the features in real-time using the python API?
I have changed the config to:
```
[waveIn:cFFmpegSource]
writer.dmLevel = wave
blocksize_sec = 1.0
filename = \cm[inputfile(I){test.wav}:name of input file]
monoMixdown = 1.0
outFieldName = pcm
```
However, it takes input from a file but I want to take input from a port.
For example, I'll be sending an audio file through 8000 port and I want to pass this input to the open smile python API

**Comment by chausner-audeering** [comment] 2021-12-11 16:45
I'm closing this issue as a duplicate of https://github.com/audeering/opensmile/issues/35. Please continue the discussion there.

**Closed by chausner-audeering** 2021-12-11 16:45 UTC
