### ISSUE TITLE
AttributeError: module 'opensmile' has no attribute 'Smile'

### ISSUE THREAD

**Issue by nmehjabin** [audeering/opensmile-python#83] opened 2023-07-19 17:55 UTC
This is the example taken from the GitHub. I am having issue running it as it says.
`import opensmile
smile = opensmile.Smile(
    feature_set=opensmile.FeatureSet.ComParE_2016,
    feature_level=opensmile.FeatureLevel.Functionals,
)
`
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 2
      1 import opensmile
----> 2 smile = opensmile.Smile(
      3     feature_set=opensmile.FeatureSet.ComParE_2016,
      4     feature_level=opensmile.FeatureLevel.Functionals,
      5 )

AttributeError: module 'opensmile' has no attribute 'Smile'

`y = smile.process_file('~/Desktop/Harvard\ list\ 01.wav')`

**Comment by hagenw** [comment] 2023-07-25 11:39
Duplicate of https://github.com/audeering/opensmile-python/issues/15

**Closed by hagenw** 2023-07-25 11:39 UTC
Labels: duplicate
